// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Task
{
    public partial class DataCleaningModel
    {
        /// <summary>
        /// model input class for DataCleaningModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"RowNumber")]
            public float RowNumber { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"CustomerId")]
            public float CustomerId { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Surname")]
            public string Surname { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"CreditScore")]
            public float CreditScore { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Geography")]
            public string Geography { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Gender")]
            public string Gender { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"Age")]
            public float Age { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"Tenure")]
            public float Tenure { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"Balance")]
            public float Balance { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"NumOfProducts")]
            public float NumOfProducts { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"HasCrCard")]
            public float HasCrCard { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"IsActiveMember")]
            public float IsActiveMember { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"EstimatedSalary")]
            public float EstimatedSalary { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"Exited")]
            public float Exited { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for DataCleaningModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"RowNumber")]
            public float RowNumber { get; set; }

            [ColumnName(@"CustomerId")]
            public float CustomerId { get; set; }

            [ColumnName(@"Surname")]
            public string Surname { get; set; }

            [ColumnName(@"CreditScore")]
            public float CreditScore { get; set; }

            [ColumnName(@"Geography")]
            public string Geography { get; set; }

            [ColumnName(@"Gender")]
            public string Gender { get; set; }

            [ColumnName(@"Age")]
            public float Age { get; set; }

            [ColumnName(@"Tenure")]
            public float Tenure { get; set; }

            [ColumnName(@"Balance")]
            public float Balance { get; set; }

            [ColumnName(@"NumOfProducts")]
            public float NumOfProducts { get; set; }

            [ColumnName(@"HasCrCard")]
            public float HasCrCard { get; set; }

            [ColumnName(@"IsActiveMember")]
            public float IsActiveMember { get; set; }

            [ColumnName(@"EstimatedSalary")]
            public float EstimatedSalary { get; set; }

            [ColumnName(@"Exited")]
            public float Exited { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("DataCleaningModel.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
