// This file was auto-generated by ML.NET Model Builder. 

using DataCleaningModel_ConsoleApp1;
using task;

// Create single instance of sample data from first line of dataset for model input
DataCleaningModel.ModelInput sampleData = new DataCleaningModel.ModelInput()
{
CreditScore = 608F,
Gender = @"Female",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual EstimatedSalary with predicted EstimatedSalary from sample data...\n\n");


Console.WriteLine($"CreditScore: {608F}");
Console.WriteLine($"Gender: {@"Female"}");
Console.WriteLine($"EstimatedSalary: {112542.6F}");


var predictionResult = DataCleaningModel.Predict(sampleData);
Console.WriteLine($"\n\nPredicted EstimatedSalary: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();


/*
var duplicatedData = new DuplicatedData("C:\\Users\\ahmed\\OneDrive\\Desktop\\Uni\\Bachelor Thesis\\sampletest.csv");
duplicatedData.PrintDuplicatedData();
Console.ReadKey();
*/